ALTER TABLE `User`
  ADD COLUMN `usaTurnosFijos` BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE `Plan`
  ADD COLUMN `duracion` VARCHAR(191) NOT NULL DEFAULT 'MENSUAL',
  ADD COLUMN `sesionesPorSemana` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `sesionesGracia` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `requiereTurno` BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE `Cuota`
  ADD COLUMN `fechaInicio` DATETIME(3) NULL,
  ADD COLUMN `fechaFin` DATETIME(3) NULL,
  ADD COLUMN `planNombreSnapshot` VARCHAR(191) NULL,
  ADD COLUMN `planDuracionSnapshot` VARCHAR(191) NULL,
  ADD COLUMN `planSesionesSemanaSnapshot` INTEGER NULL,
  ADD COLUMN `planSesionesGraciaSnapshot` INTEGER NULL,
  ADD COLUMN `planRequiereTurnoSnapshot` BOOLEAN NULL,
  ADD COLUMN `ID_Plan` INTEGER NULL;

ALTER TABLE `Turno`
  ADD COLUMN `origen` VARCHAR(191) NOT NULL DEFAULT 'MANUAL',
  ADD COLUMN `canceladoEn` DATETIME(3) NULL,
  ADD COLUMN `ID_Cuota` INTEGER NULL;

ALTER TABLE `Asistencia`
  ADD COLUMN `ID_Turno` INTEGER NULL,
  ADD COLUMN `ID_Cuota` INTEGER NULL;

CREATE TABLE `TurnoFijo` (
  `ID_TurnoFijo` INTEGER NOT NULL AUTO_INCREMENT,
  `ID_Usuario` INTEGER NOT NULL,
  `ID_HorarioClase` INTEGER NOT NULL,
  `activo` BOOLEAN NOT NULL DEFAULT true,
  `fechaCreacion` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

  UNIQUE INDEX `TurnoFijo_ID_Usuario_ID_HorarioClase_key`(`ID_Usuario`, `ID_HorarioClase`),
  PRIMARY KEY (`ID_TurnoFijo`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE `Cuota`
  ADD CONSTRAINT `Cuota_ID_Plan_fkey` FOREIGN KEY (`ID_Plan`) REFERENCES `Plan`(`ID_Plan`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `Turno`
  ADD CONSTRAINT `Turno_ID_Cuota_fkey` FOREIGN KEY (`ID_Cuota`) REFERENCES `Cuota`(`ID_Cuota`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `Asistencia`
  ADD CONSTRAINT `Asistencia_ID_Turno_fkey` FOREIGN KEY (`ID_Turno`) REFERENCES `Turno`(`id_turno`) ON DELETE SET NULL ON UPDATE CASCADE,
  ADD CONSTRAINT `Asistencia_ID_Cuota_fkey` FOREIGN KEY (`ID_Cuota`) REFERENCES `Cuota`(`ID_Cuota`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `TurnoFijo`
  ADD CONSTRAINT `TurnoFijo_ID_Usuario_fkey` FOREIGN KEY (`ID_Usuario`) REFERENCES `User`(`ID_Usuario`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `TurnoFijo_ID_HorarioClase_fkey` FOREIGN KEY (`ID_HorarioClase`) REFERENCES `HorarioClase`(`ID_HorarioClase`) ON DELETE CASCADE ON UPDATE CASCADE;
